# Create input dataset to use in bounded mortality method: ----

# Load packages ----

if(!require("pacman")) install.packages("pacman")

pacman::p_load(here, glue, dplyr, tidyr, purrr, haven)

rm(list = ls())

# Constants ----

wd <- here()
cnst <- list()

cnst <- within(cnst, {
  path_out = glue('{wd}/Out')
  path_tmp = glue('{wd}/tmp')
})

# Load datasets

pop_deaths_2017 <- readRDS(glue('{wd}/Out/pop_deaths_2017.rds'))
educ_females <- readRDS(glue('{wd}/Data_folder/educ_females.rds'))
educ_males <- readRDS(glue('{wd}/Data_folder/educ_males.rds'))

# Merge education datasets

educ_females <- educ_females %>% 
  mutate(sex = rep(2,length(year)))

educ_males <- educ_males %>% 
  mutate(sex = rep(1,length(year)))

educ <- educ_males %>% 
  bind_rows(educ_females)

# Recategorization of the variable years_ed (educational attainment)

educ <- educ %>% 
  mutate(years_ed = case_when(
    years_ed >= 1 & years_ed <= 6 ~ 1,
    years_ed >= 7 & years_ed <= 12 ~ 2,
    years_ed >= 13 & years_ed <= 16 ~ 3,
    years_ed >= 17 & years_ed <= 20 ~ 4,
    TRUE ~ 0
  )) %>% 
  group_by(sex, year, years_ed) %>% 
  summarise(p = sum(p))

# Creation of the mortality rate variable per 100,000 population (population-based dataset) 

pop_deaths_2017 <- pop_deaths_2017 %>% 
  mutate(rate = n_deaths/n_census * 100000)

# Create input dataset according to each approach ----

# 1. Cohort ----

# Estimation of the proportion of individuals by sex, age, and education strata

cohort <- pop_deaths_2017 %>% 
  group_by(sex, age) %>% 
  summarise(total_pop = sum(n_census, na.rm = TRUE), .groups = "drop")

cohort <- pop_deaths_2017 %>%
  left_join(cohort, by = c("sex", "age")) %>% 
  mutate(p = n_census/total_pop) %>% 
  select(-total_pop)

# Ridit score estimation

cohort <- cohort %>% 
  group_by(sex, age) %>% 
  mutate(cum_p = cumsum(p), # Cumulative distribution
         r_mid = ifelse(row_number() == 1, cum_p/2, (cum_p + lag(cum_p)) / 2), # Ridit estimation
         rank = r_mid * 100) %>% # Ridit score scaled by 100
  arrange(sex, age)

# Save as .dta file

write_dta(cohort, path = glue('{cnst$path_out}/mortality_rates_2017_ranked_cohort.dta'))

# 2. Period ----

# Estimation of the proportion of individuals by sex and education strata

period_pop <- pop_deaths_2017 %>% 
  group_by(sex) %>% 
  summarize(total_pop = sum(n_census, na.rm = TRUE), .groups = "drop")

period_num <- pop_deaths_2017 %>% 
  group_by(sex, years_ed) %>% 
  summarize(n_census = sum(n_census, na.rm = TRUE), .groups = "drop")

period <- pop_deaths_2017 %>% 
  select(-n_census) %>% 
  left_join(period_pop, by = "sex") %>% 
  left_join(period_num, by = c("sex","years_ed")) %>% 
  mutate(p = n_census/total_pop)

period <- period %>% 
  group_by(sex, age) %>% 
  mutate(cum_p = cumsum(p), # Cumulative distribution
         r_mid = ifelse(row_number() == 1, cum_p/2, (cum_p + lag(cum_p)) / 2), # Ridit estimation
         rank = r_mid * 100) %>% # Ridit score scaled by 100
  select(-total_pop) %>% 
  arrange(sex, age) %>% 
  relocate(n_census, .after = years_ed)

# Save as .dta file

write_dta(period, path = glue('{cnst$path_out}/mortality_rates_2017_ranked_period.dta'))

# 3. Lagged cohort ----

# Estimation of the proportion of individuals by sex, age, and education strata

lagged_cohort <- pop_deaths_2017 %>%
  mutate(year = 2017 - age + 26)

lagged_cohort <- lagged_cohort %>%
  left_join(educ, by = c("sex", "years_ed", "year"))

lagged_cohort <- lagged_cohort %>% 
  group_by(sex,age) %>% 
  mutate(cum_p = cumsum(p), # Cumulative distribution
         r_mid = ifelse(row_number() == 1, cum_p/2, (cum_p + lag(cum_p)) / 2), # Ridit estimation
         rank = r_mid * 100) %>% # Ridit score scaled by 100
  select(-year) %>% 
  arrange(sex, age)

# Save as .dta file

write_dta(lagged_cohort, path = glue('{cnst$path_out}/mortality_rates_2017_ranked_lagged_cohort.dta'))

rm(list = ls())

# ==============================================================================
# NOTE ON NEXT WORKFLOW STEP
# ==============================================================================
#
# The output datasets generated by this script (saved as .dta files) are used
# as inputs for the Stata workflow that produces the mortality bounds.
#
# These files must be used when running the following Stata programs:
#
#   7. Programs.do
#   7.1 Cohort_mortality_q.do
#   7.2 Lagged_cohort_mortality_q.do
#   7.3 Period_mortality_q.do
#
# Ensure that the .dta outputs produced by this script are available in the
# expected directory before executing the Stata scripts.
#
# ==============================================================================
