# Life tables and life expectancy estimations using bounded mortality method: ----
# ==============================================================================
# NOTE ON INPUT DATA
# ==============================================================================
#
# This script requires input datasets that are generated in Stata prior to
# running the R workflow. These datasets must be created by executing the
# following Stata do-files:
#
#   7.1 Cohort_mortality_q.do
#   7.2 Lagged_cohort_mortality_q.do
#   7.3 Period_mortality_q.do
#
# The do-files produce the expected number of deaths per 100,000 population by age, sex, and quintile
# (lower and upper bounds), which are used as inputs for the life table calculations in this script.
#
# IMPORTANT:
# The output datasets generated by the Stata scripts must be saved in the
# directory defined as `cnst$path_out` (the "Out" folder) before running this
# R script.
#
# In the Stata workflow, the outputs are saved using commands such as:
#
#   save "Out/mortality_bounds_by_age_sex_quintile_cohort.dta", replace
#
# These files must be available in the "Out" directory so that they can be
# loaded and processed by the R life table workflow.
#
# ==============================================================================

# Load packages ----

if(!require("pacman")) install.packages("pacman")

pacman::p_load(here, glue, dplyr, haven, rlang, purrr)

rm(list = ls())

# Constants ----

wd <- here()
cnst <- list()

cnst <- within(cnst, {
  path_out = glue('{wd}/Out')
  path_tmp = glue('{wd}/tmp')
})

# Load datasets ----

cohort <- read_dta(glue('{wd}/Out/mortality_bounds_by_age_sex_quintile_cohort.dta')) # cohort
lagged_cohort <- read_dta(glue('{wd}/Out/mortality_bounds_by_age_sex_quintile_lagged_cohort.dta')) # lagged cohort
period <- read_dta(glue('{wd}/Out/mortality_bounds_by_age_sex_quintile_period.dta')) # period

# Derive mortality rates as input for the life table (mx).
# The variables mort_lb and mort_ub represent the expected number of deaths per 100,000 population (lower and upper bound, respectively);
# therefore, they must be divided by 100,000 to obtain the mortality rates.

cohort <- cohort %>% 
  mutate(rate_lb = mort_lb/100000, # lower bound rate
         rate_ub = mort_ub/100000) # upper bound rate

lagged_cohort <- lagged_cohort %>% 
  mutate(rate_lb = mort_lb/100000, # lower bound rate
         rate_ub = mort_ub/100000) # upper bound rate

period <- period %>% 
  mutate(rate_lb = mort_lb/100000, # lower bound rate
         rate_ub = mort_ub/100000) # upper bound rate

# Life table function ----

CalculateLifeTable <- function(df, x, nx = c(rep(1, 74), Inf), mx) {
  
  df %>%
    transmute(
      x  = {{ x }},
      nx = nx,
      mx = {{ mx }},
      px = exp(-mx * nx),
      qx = 1 - px,
      lx = head(cumprod(c(1, px)), -1),
      dx = c(-diff(lx), tail(lx, 1)),
      Lx = if_else(mx <= 0, lx * nx, dx / mx),
      Tx = rev(cumsum(rev(Lx))),
      ex = Tx / lx,
      sd0 = c(sqrt(sum(dx * (x + 0.5 - ex[1])^2)), rep(0, length(x) - 1))
    )
}

# Build a life table using a selected mortality rate variable ----

build_life_table <- function(data, rate_var) {
  
  rate_sym <- sym(rate_var)
  
  data %>%
    arrange(quintile, sex, age) %>%
    group_by(quintile, sex) %>%
    group_modify(~ CalculateLifeTable(.x, x = age, mx = !!rate_sym)) %>%
    ungroup()
}

# Process one dataset:
# 1. Build life tables using rate_lb and rate_ub
# 2. Construct a consolidated life expectancy dataset
# 3. Save outputs as .rds files

process_life_tables_named <- function(data, method, out_dir = cnst$path_out) {
  
  # Define the mortality rate variables associated with each life table bound
  
  rate_vars <- c(lower = "rate_lb", upper = "rate_ub")
  
  # Build life tables for both mortality rate bounds
  
  life_tables <- imap(rate_vars, ~ build_life_table(data, .x))
  
  # Construct a consolidated dataset of life expectancy estimates
  # rate_ub -> higher mortality -> lower life expectancy (low_ex)
  # rate_lb -> lower mortality  -> upper life expectancy (upper_ex)
  
  life_expectancy_summary <- life_tables$upper %>%
    select(sex, x, quintile, ex) %>%
    rename(low_ex = ex) %>%
    left_join(
      life_tables$lower %>%
        select(sex, x, quintile, ex) %>%
        rename(upper_ex = ex),
      by = c("sex", "x", "quintile")
    )
  
  # Define output file names
  
  file_lower <- glue("{out_dir}/{method}_life_table_lower_bounds.rds")
  file_upper <- glue("{out_dir}/{method}_life_table_upper_bounds.rds")
  file_ex    <- glue("{out_dir}/{method}_life_expectancy_lower_upper.rds")
  
  # Save outputs
  
  saveRDS(life_tables$lower, file = file_lower)
  saveRDS(life_tables$upper, file = file_upper)
  saveRDS(life_expectancy_summary, file = file_ex)
  
  # Return outputs in memory
  
  list(
    method = method,
    life_tables = life_tables,
    life_expectancy_summary = life_expectancy_summary,
    files = c(
      lower_bounds = file_lower,
      upper_bounds = file_upper,
      life_expectancy = file_ex
    )
  )
}

# Store all input datasets in a named list ----

methods_data <- list(
  cohort = cohort,
  lagged_cohort = lagged_cohort,
  period = period
)

# Run the full workflow for all methods ----

results_life_tables <- imap(
  methods_data,
  ~ process_life_tables_named(
    data = .x,
    method = .y,
    out_dir = cnst$path_out
  )
)

rm(list = ls())
